-- Quiz system upgrade: recategorize the original seed quiz under the new
-- 6-category taxonomy shared with Podcasts, then seed 14 more quizzes (5
-- questions each) so there are 15 quizzes total, 2-3 per category.

update quizzes set category = 'starting_a_business' where id = '00000000-0000-0000-0000-000000000001';

insert into quizzes (id, title, description, category, min_level, question_count, time_limit_seconds, xp_reward, is_active)
values
  ('00000000-0000-0000-0000-000000000002', 'Finding Your Business Idea', 'How to spot a real problem worth solving.', 'starting_a_business', 1, 5, 120, 40, true),
  ('00000000-0000-0000-0000-000000000003', 'Writing a Simple Business Plan', 'The basics of planning before you launch.', 'starting_a_business', 4, 5, 120, 45, true),
  ('00000000-0000-0000-0000-000000000004', 'Marketing Basics', 'What marketing actually means for a small business.', 'marketing_branding', 2, 5, 120, 40, true),
  ('00000000-0000-0000-0000-000000000005', 'Social Media for Business', 'Using social platforms to grow an audience.', 'marketing_branding', 3, 5, 120, 45, true),
  ('00000000-0000-0000-0000-000000000006', 'Building a Brand', 'What makes a brand memorable and trustworthy.', 'marketing_branding', 6, 5, 120, 50, true),
  ('00000000-0000-0000-0000-000000000007', 'Budgeting Basics', 'Managing money in and money out.', 'money_finance', 2, 5, 120, 40, true),
  ('00000000-0000-0000-0000-000000000008', 'Understanding Profit & Loss', 'How businesses know if they''re actually making money.', 'money_finance', 5, 5, 120, 45, true),
  ('00000000-0000-0000-0000-000000000009', 'Leadership Fundamentals', 'What makes someone worth following.', 'leadership_teams', 3, 5, 120, 40, true),
  ('00000000-0000-0000-0000-000000000010', 'Working in a Team', 'Getting the best out of working with others.', 'leadership_teams', 1, 5, 120, 35, true),
  ('00000000-0000-0000-0000-000000000011', 'Famous Founder Stories', 'Lessons from well-known entrepreneurs.', 'founder_stories', 1, 5, 120, 35, true),
  ('00000000-0000-0000-0000-000000000012', 'Learning From Failure', 'Why setbacks are part of every founder''s story.', 'founder_stories', 4, 5, 120, 45, true),
  ('00000000-0000-0000-0000-000000000013', 'Intro to Digital Tools', 'The apps and sites founders use every day.', 'digital_tech', 1, 5, 120, 35, true),
  ('00000000-0000-0000-0000-000000000014', 'Website & App Basics', 'What goes into building your first website.', 'digital_tech', 5, 5, 120, 45, true),
  ('00000000-0000-0000-0000-000000000015', 'Staying Safe Online', 'Protecting yourself and your business online.', 'digital_tech', 1, 5, 120, 35, true)
on conflict (id) do nothing;

insert into quiz_questions (quiz_id, question_text, options, explanation, order_index) values
-- Finding Your Business Idea (002)
('00000000-0000-0000-0000-000000000002', 'What''s usually the best sign that a business idea is worth pursuing?', '[{"text":"People have a real problem it solves","is_correct":true},{"text":"It sounds cool to your friends","is_correct":false},{"text":"No one else is doing it","is_correct":false},{"text":"It requires very little effort","is_correct":false}]'::jsonb, 'Ideas that solve a real, felt problem are far more likely to find paying customers.', 0),
('00000000-0000-0000-0000-000000000002', 'What is a common way to find business ideas?', '[{"text":"Look at problems in your own daily life","is_correct":true},{"text":"Wait for inspiration to strike randomly","is_correct":false},{"text":"Copy a business exactly with no changes","is_correct":false},{"text":"Only ask family what they think","is_correct":false}]'::jsonb, 'Your own frustrations and daily experiences are often the richest source of ideas.', 1),
('00000000-0000-0000-0000-000000000002', 'Why is it useful to talk to potential customers early?', '[{"text":"To find out if they''d actually pay for a solution","is_correct":true},{"text":"To get free advertising immediately","is_correct":false},{"text":"Because it''s legally required","is_correct":false},{"text":"To avoid ever changing the idea","is_correct":false}]'::jsonb, 'Early conversations tell you whether the problem is painful enough that people would pay to fix it.', 2),
('00000000-0000-0000-0000-000000000002', 'What does "niche" mean in business?', '[{"text":"A small, specific group of customers with a shared need","is_correct":true},{"text":"A type of business plan document","is_correct":false},{"text":"The total size of a market","is_correct":false},{"text":"A legal business structure","is_correct":false}]'::jsonb, 'A niche is a focused slice of a market — often easier to win than trying to serve everyone.', 3),
('00000000-0000-0000-0000-000000000002', 'What is a "competitor"?', '[{"text":"Another business solving a similar problem for similar customers","is_correct":true},{"text":"Anyone who dislikes your idea","is_correct":false},{"text":"A customer who complains","is_correct":false},{"text":"A business partner","is_correct":false}]'::jsonb, 'Understanding your competitors helps you figure out what makes your idea different.', 4),

-- Writing a Simple Business Plan (003)
('00000000-0000-0000-0000-000000000003', 'What is the main purpose of a business plan?', '[{"text":"To think through how the business will actually work and make money","is_correct":true},{"text":"To make the idea sound impressive","is_correct":false},{"text":"To copy a template exactly","is_correct":false},{"text":"To avoid ever changing direction","is_correct":false}]'::jsonb, 'A business plan is mainly a thinking tool — it forces you to work through the details before you spend time and money.', 0),
('00000000-0000-0000-0000-000000000003', 'Which of these best describes a "target market"?', '[{"text":"The specific group of people most likely to buy from you","is_correct":true},{"text":"Every person in the country","is_correct":false},{"text":"A competitor''s customer list","is_correct":false},{"text":"The place where you sell products","is_correct":false}]'::jsonb, 'Your target market is the group whose needs your product is actually built for.', 1),
('00000000-0000-0000-0000-000000000003', 'What does "revenue" mean?', '[{"text":"The total money a business brings in from sales","is_correct":true},{"text":"The money left after all expenses","is_correct":false},{"text":"A type of business loan","is_correct":false},{"text":"The cost of making a product","is_correct":false}]'::jsonb, 'Revenue is money in before any costs are subtracted — profit is what''s left after costs.', 2),
('00000000-0000-0000-0000-000000000003', 'Why should a business plan include costs, not just the idea?', '[{"text":"So you know if the business can realistically be profitable","is_correct":true},{"text":"Because investors like long documents","is_correct":false},{"text":"To make the plan look official","is_correct":false},{"text":"Costs aren''t actually important early on","is_correct":false}]'::jsonb, 'A great idea only works as a business if the numbers add up — costs vs. what people will pay.', 3),
('00000000-0000-0000-0000-000000000003', 'What is a reasonable first step after writing a simple plan?', '[{"text":"Test the smallest version of the idea with real people","is_correct":true},{"text":"Immediately spend all your savings on it","is_correct":false},{"text":"Wait a year before doing anything","is_correct":false},{"text":"Never update the plan again","is_correct":false}]'::jsonb, 'Small, quick tests tell you fast whether the plan matches reality.', 4),

-- Marketing Basics (004)
('00000000-0000-0000-0000-000000000004', 'What is marketing, at its core?', '[{"text":"Communicating why your product matters to the right people","is_correct":true},{"text":"Only paid adverts on social media","is_correct":false},{"text":"Making your logo look nice","is_correct":false},{"text":"Selling to absolutely everyone","is_correct":false}]'::jsonb, 'Marketing is about connecting the right message with the right audience — ads are just one tool.', 0),
('00000000-0000-0000-0000-000000000004', 'What is a "target audience"?', '[{"text":"The specific people most likely to want what you offer","is_correct":true},{"text":"Anyone who follows you online","is_correct":false},{"text":"A group of competitors","is_correct":false},{"text":"People who have already bought once","is_correct":false}]'::jsonb, 'Knowing exactly who you''re talking to makes every marketing message more effective.', 1),
('00000000-0000-0000-0000-000000000004', 'Why do businesses use "word of mouth" marketing?', '[{"text":"People trust recommendations from people they know","is_correct":true},{"text":"It costs more than paid ads","is_correct":false},{"text":"It only works for large companies","is_correct":false},{"text":"It requires no good product","is_correct":false}]'::jsonb, 'Recommendations from friends and family carry more trust than most advertising.', 2),
('00000000-0000-0000-0000-000000000004', 'What''s a simple way to test if a marketing message works?', '[{"text":"Try it with a small group and see how they respond","is_correct":true},{"text":"Guess based on personal opinion only","is_correct":false},{"text":"Only ask people who already love your brand","is_correct":false},{"text":"Never test — just go with your first idea","is_correct":false}]'::jsonb, 'Small tests let you learn what resonates before investing in a bigger campaign.', 3),
('00000000-0000-0000-0000-000000000004', 'What does a "call to action" do?', '[{"text":"Tells the reader exactly what to do next","is_correct":true},{"text":"Describes the founder''s life story","is_correct":false},{"text":"Lists every feature of a product","is_correct":false},{"text":"Explains a company''s history","is_correct":false}]'::jsonb, 'A clear call to action ("Sign up", "Buy now") makes it obvious what step to take next.', 4),

-- Social Media for Business (005)
('00000000-0000-0000-0000-000000000005', 'Why might a business post consistently on social media?', '[{"text":"To stay visible and build trust with an audience over time","is_correct":true},{"text":"Because posting once guarantees success","is_correct":false},{"text":"It''s required by law","is_correct":false},{"text":"To copy every competitor exactly","is_correct":false}]'::jsonb, 'Consistency helps an audience remember you and builds familiarity, which builds trust.', 0),
('00000000-0000-0000-0000-000000000005', 'What is "engagement" on social media?', '[{"text":"Likes, comments, shares, and other interactions with a post","is_correct":true},{"text":"The number of followers only","is_correct":false},{"text":"How long an account has existed","is_correct":false},{"text":"The number of hashtags used","is_correct":false}]'::jsonb, 'Engagement measures how people actually interact with your content, not just how many see it.', 1),
('00000000-0000-0000-0000-000000000005', 'Which is generally a stronger social media strategy?', '[{"text":"Posting content that solves a problem or entertains your audience","is_correct":true},{"text":"Only posting about how great your product is","is_correct":false},{"text":"Buying fake followers","is_correct":false},{"text":"Posting on every platform with identical content","is_correct":false}]'::jsonb, 'Genuinely useful or entertaining content earns attention — pure self-promotion usually doesn''t.', 2),
('00000000-0000-0000-0000-000000000005', 'What should you always keep in mind when posting as a business?', '[{"text":"Whether the content matches your brand and is appropriate for your audience","is_correct":true},{"text":"Posting as often as physically possible","is_correct":false},{"text":"Copying whatever is trending exactly","is_correct":false},{"text":"Ignoring comments from followers","is_correct":false}]'::jsonb, 'Staying on-brand and audience-appropriate keeps trust intact as you grow.', 3),
('00000000-0000-0000-0000-000000000005', 'Why might a young founder ask a trusted adult before posting publicly?', '[{"text":"To get a second opinion on safety and appropriateness","is_correct":true},{"text":"Because it''s illegal to post without permission","is_correct":false},{"text":"It guarantees more followers","is_correct":false},{"text":"It''s required by every platform","is_correct":false}]'::jsonb, 'A second opinion helps catch anything unsafe or unintentionally embarrassing before it''s public.', 4),

-- Building a Brand (006)
('00000000-0000-0000-0000-000000000006', 'What is a "brand", really?', '[{"text":"The overall feeling and reputation people associate with a business","is_correct":true},{"text":"Just a logo","is_correct":false},{"text":"A legal registration document","is_correct":false},{"text":"The price of a product","is_correct":false}]'::jsonb, 'A brand is bigger than a logo — it''s the feeling and trust people build around your business.', 0),
('00000000-0000-0000-0000-000000000006', 'Why does consistency matter in branding (colours, tone, style)?', '[{"text":"It makes a business instantly recognisable","is_correct":true},{"text":"It has no real effect on customers","is_correct":false},{"text":"It''s only important for huge companies","is_correct":false},{"text":"It limits creativity, so it should be avoided","is_correct":false}]'::jsonb, 'Consistent visuals and tone help people recognise and remember you across every touchpoint.', 1),
('00000000-0000-0000-0000-000000000006', 'What is "brand voice"?', '[{"text":"The consistent tone and style used in how a business communicates","is_correct":true},{"text":"The literal sound of a business''s phone line","is_correct":false},{"text":"A jingle used in ads","is_correct":false},{"text":"The founder''s personal opinions","is_correct":false}]'::jsonb, 'Brand voice is how a business "sounds" in its writing — friendly, bold, formal, playful, etc.', 2),
('00000000-0000-0000-0000-000000000006', 'Why might a brand choose specific colours deliberately?', '[{"text":"Colours can influence how people feel about a brand","is_correct":true},{"text":"Colour choice has zero psychological effect","is_correct":false},{"text":"To match whatever is cheapest to print","is_correct":false},{"text":"Because regulations require certain colours","is_correct":false}]'::jsonb, 'Colour psychology is a real part of design — different colours evoke different feelings and associations.', 3),
('00000000-0000-0000-0000-000000000006', 'What builds long-term brand trust the most?', '[{"text":"Consistently delivering on what you promise","is_correct":true},{"text":"A flashy one-time advert","is_correct":false},{"text":"Changing your logo often","is_correct":false},{"text":"Having the lowest price always","is_correct":false}]'::jsonb, 'Trust is built over time by consistently keeping promises to customers.', 4),

-- Budgeting Basics (007)
('00000000-0000-0000-0000-000000000007', 'What is a budget?', '[{"text":"A plan for how money will be earned and spent","is_correct":true},{"text":"A type of bank account","is_correct":false},{"text":"A legal business licence","is_correct":false},{"text":"A tax form","is_correct":false}]'::jsonb, 'A budget is simply a plan that maps out expected money in and money out.', 0),
('00000000-0000-0000-0000-000000000007', 'What are "expenses"?', '[{"text":"Money spent to run the business","is_correct":true},{"text":"Money earned from customers","is_correct":false},{"text":"Money saved in a bank","is_correct":false},{"text":"A type of business idea","is_correct":false}]'::jsonb, 'Expenses are costs — things like materials, tools, or fees needed to operate.', 1),
('00000000-0000-0000-0000-000000000007', 'Why is it smart to track spending, even for a small side business?', '[{"text":"So you know whether you''re actually making or losing money","is_correct":true},{"text":"Tracking spending is legally pointless for small amounts","is_correct":false},{"text":"It only matters once you''re very large","is_correct":false},{"text":"It guarantees you''ll never lose money","is_correct":false}]'::jsonb, 'Without tracking, it''s easy to think you''re profitable when you''re actually not.', 2),
('00000000-0000-0000-0000-000000000007', 'What does it mean to "save before you spend"?', '[{"text":"Setting money aside first, before spending on wants","is_correct":true},{"text":"Never spending any money at all","is_correct":false},{"text":"Spending everything, then saving what''s left (which is often nothing)","is_correct":false},{"text":"Only saving money you find by accident","is_correct":false}]'::jsonb, 'Saving first builds a habit and a safety net, rather than hoping there''s something left over.', 3),
('00000000-0000-0000-0000-000000000007', 'What is a simple way to categorise business spending?', '[{"text":"Separate essential costs from optional extras","is_correct":true},{"text":"Treat every expense as equally important","is_correct":false},{"text":"Avoid categorising, just track a total","is_correct":false},{"text":"Only track spending over £100","is_correct":false}]'::jsonb, 'Splitting essential vs. optional spending makes it much easier to cut costs when needed.', 4),

-- Understanding Profit & Loss (008)
('00000000-0000-0000-0000-000000000008', 'What is "profit"?', '[{"text":"Revenue minus all costs and expenses","is_correct":true},{"text":"The total amount of sales made","is_correct":false},{"text":"Money borrowed from a bank","is_correct":false},{"text":"The price of a single product","is_correct":false}]'::jsonb, 'Profit is what''s actually left over after you subtract every cost from your revenue.', 0),
('00000000-0000-0000-0000-000000000008', 'If a business has high revenue but even higher costs, what happens?', '[{"text":"It runs at a loss, even though sales look good","is_correct":true},{"text":"It automatically becomes profitable","is_correct":false},{"text":"Revenue and costs cancel out to zero every time","is_correct":false},{"text":"It has no effect on the business at all","is_correct":false}]'::jsonb, 'Sales alone don''t tell the full story — costs have to be lower than revenue to turn a profit.', 1),
('00000000-0000-0000-0000-000000000008', 'What is "profit margin"?', '[{"text":"Profit shown as a percentage of revenue","is_correct":true},{"text":"The total number of items sold","is_correct":false},{"text":"A discount offered to customers","is_correct":false},{"text":"The cost of shipping a product","is_correct":false}]'::jsonb, 'Profit margin shows how much of every pound in sales actually turns into profit.', 2),
('00000000-0000-0000-0000-000000000008', 'Why might a business intentionally accept a loss early on?', '[{"text":"To invest in growth before becoming profitable later","is_correct":true},{"text":"Because losses are always good for a business","is_correct":false},{"text":"It has no strategic reason ever","is_correct":false},{"text":"To avoid paying any taxes forever","is_correct":false}]'::jsonb, 'Some businesses spend more than they earn early on to build something bigger long-term — but it''s a deliberate, tracked choice.', 3),
('00000000-0000-0000-0000-000000000008', 'Which of these would increase profit, all else being equal?', '[{"text":"Reducing unnecessary costs","is_correct":true},{"text":"Increasing costs with no extra sales","is_correct":false},{"text":"Giving away products for free","is_correct":false},{"text":"Ignoring expenses completely","is_correct":false}]'::jsonb, 'Cutting unnecessary costs directly increases what''s left over as profit.', 4),

-- Leadership Fundamentals (009)
('00000000-0000-0000-0000-000000000009', 'What makes someone a good leader, most of the time?', '[{"text":"Listening to others and making thoughtful decisions","is_correct":true},{"text":"Always being the loudest person in the room","is_correct":false},{"text":"Never asking for anyone''s opinion","is_correct":false},{"text":"Taking credit for the whole team''s work","is_correct":false}]'::jsonb, 'Strong leaders listen and involve others, which builds trust and better decisions.', 0),
('00000000-0000-0000-0000-000000000009', 'Why is clear communication important for a leader?', '[{"text":"It helps everyone understand what''s expected of them","is_correct":true},{"text":"It''s only useful in large companies","is_correct":false},{"text":"Vague instructions always work out fine","is_correct":false},{"text":"It''s not actually a leadership skill","is_correct":false}]'::jsonb, 'Clear communication avoids confusion and helps a team move in the same direction.', 1),
('00000000-0000-0000-0000-000000000009', 'How should a good leader handle a mistake they made?', '[{"text":"Own it honestly and figure out how to fix it","is_correct":true},{"text":"Blame someone else on the team","is_correct":false},{"text":"Pretend it didn''t happen","is_correct":false},{"text":"Quit immediately","is_correct":false}]'::jsonb, 'Owning mistakes builds trust and models honesty for the whole team.', 2),
('00000000-0000-0000-0000-000000000009', 'What does it mean to "lead by example"?', '[{"text":"Doing the things you ask others to do","is_correct":true},{"text":"Only giving instructions, never doing the work yourself","is_correct":false},{"text":"Being the only one who makes decisions","is_correct":false},{"text":"Avoiding any hands-on work","is_correct":false}]'::jsonb, 'When a leader''s actions match their words, the team is far more likely to follow.', 3),
('00000000-0000-0000-0000-000000000009', 'Why is it valuable for a leader to recognise their team''s effort?', '[{"text":"It builds motivation and trust","is_correct":true},{"text":"Recognition has no real effect on people","is_correct":false},{"text":"It should only happen once a year","is_correct":false},{"text":"It makes the leader look weak","is_correct":false}]'::jsonb, 'Feeling appreciated is one of the biggest motivators for people doing good work.', 4),

-- Working in a Team (010)
('00000000-0000-0000-0000-000000000010', 'What''s a healthy way to handle a disagreement with a teammate?', '[{"text":"Talk it through calmly and listen to their point of view","is_correct":true},{"text":"Ignore them until the problem goes away","is_correct":false},{"text":"Complain about them to everyone else","is_correct":false},{"text":"Insist you''re right without listening","is_correct":false}]'::jsonb, 'Calm, direct conversation resolves disagreements far better than avoidance or conflict.', 0),
('00000000-0000-0000-0000-000000000010', 'Why do teams usually get more done than one person alone?', '[{"text":"Different people bring different skills and ideas","is_correct":true},{"text":"Teams never disagree, so things move faster","is_correct":false},{"text":"One person always does all the real work","is_correct":false},{"text":"Teams are only useful for very large projects","is_correct":false}]'::jsonb, 'Combining different strengths usually produces better results than one person working alone.', 1),
('00000000-0000-0000-0000-000000000010', 'What does being "reliable" on a team mean?', '[{"text":"Doing what you said you would, on time","is_correct":true},{"text":"Only helping when it''s convenient","is_correct":false},{"text":"Being the loudest voice in meetings","is_correct":false},{"text":"Never asking questions","is_correct":false}]'::jsonb, 'Reliability — following through on commitments — is one of the most valued traits in any team.', 2),
('00000000-0000-0000-0000-000000000010', 'What is a good way to give feedback to a teammate?', '[{"text":"Be specific, kind, and focused on the work, not the person","is_correct":true},{"text":"Criticise them in front of others","is_correct":false},{"text":"Avoid giving feedback at all","is_correct":false},{"text":"Only point out what went wrong, never what went well","is_correct":false}]'::jsonb, 'Specific, kind feedback helps people improve without feeling attacked.', 3),
('00000000-0000-0000-0000-000000000010', 'Why might a team set clear roles from the start?', '[{"text":"So everyone knows what they''re responsible for","is_correct":true},{"text":"To make sure only one person ever does anything","is_correct":false},{"text":"Roles don''t actually matter in small teams","is_correct":false},{"text":"To avoid ever having to communicate","is_correct":false}]'::jsonb, 'Clear roles reduce confusion and duplicated effort, so the team moves faster.', 4),

-- Famous Founder Stories (011)
('00000000-0000-0000-0000-000000000011', 'What do most successful founder stories have in common?', '[{"text":"They faced setbacks and kept going anyway","is_correct":true},{"text":"They succeeded on their very first attempt","is_correct":false},{"text":"They never had to change their original idea","is_correct":false},{"text":"They worked completely alone the whole time","is_correct":false}]'::jsonb, 'Nearly every well-known founder story includes real setbacks that they worked through.', 0),
('00000000-0000-0000-0000-000000000011', 'Why do many founders start with a small, simple version of their idea?', '[{"text":"To test if it works before investing more time and money","is_correct":true},{"text":"Because big ideas are illegal to start with","is_correct":false},{"text":"Small versions are always the final product","is_correct":false},{"text":"It guarantees instant success","is_correct":false}]'::jsonb, 'Starting small lets founders learn and adjust with less risk before going bigger.', 1),
('00000000-0000-0000-0000-000000000011', 'What role does "persistence" usually play in founder stories?', '[{"text":"A major one — most founders kept going after early rejection","is_correct":true},{"text":"None — persistence rarely matters","is_correct":false},{"text":"It only matters for tech companies","is_correct":false},{"text":"Persistence usually makes things worse","is_correct":false}]'::jsonb, 'Rejection and setbacks are common — what separates many successful founders is not giving up.', 2),
('00000000-0000-0000-0000-000000000011', 'Why might a founder pivot (change direction) from their original idea?', '[{"text":"Because they learned something that changed what customers actually needed","is_correct":true},{"text":"Pivoting is always a sign of failure","is_correct":false},{"text":"To make the business plan longer","is_correct":false},{"text":"Founders are legally required to pivot once","is_correct":false}]'::jsonb, 'A pivot is often a smart response to new information, not a failure.', 3),
('00000000-0000-0000-0000-000000000011', 'What can young founders learn from studying business history?', '[{"text":"Patterns in what tends to work and what doesn''t","is_correct":true},{"text":"Nothing useful — every business is completely different","is_correct":false},{"text":"That only adults can start successful businesses","is_correct":false},{"text":"That ideas never need to change","is_correct":false}]'::jsonb, 'Studying other founders'' journeys reveals patterns that can help you avoid common mistakes.', 4),

-- Learning From Failure (012)
('00000000-0000-0000-0000-000000000012', 'What is the healthiest way to think about a failed attempt?', '[{"text":"As useful information about what to try differently next","is_correct":true},{"text":"As proof you should give up entirely","is_correct":false},{"text":"As something to hide from everyone","is_correct":false},{"text":"As a sign the idea was always impossible","is_correct":false}]'::jsonb, 'Treating failure as feedback — not a verdict — is what lets founders improve and keep going.', 0),
('00000000-0000-0000-0000-000000000012', 'Why is it useful to reflect after something goes wrong?', '[{"text":"It helps you figure out what to change next time","is_correct":true},{"text":"Reflection has no real value","is_correct":false},{"text":"It''s only useful for huge failures","is_correct":false},{"text":"It guarantees the same mistake won''t happen","is_correct":false}]'::jsonb, 'Reflection turns a setback into a lesson you can actually apply going forward.', 1),
('00000000-0000-0000-0000-000000000012', 'What''s a healthy response to criticism of your idea?', '[{"text":"Consider it honestly, even if it''s hard to hear","is_correct":true},{"text":"Dismiss all criticism immediately","is_correct":false},{"text":"Only listen to people who agree with you","is_correct":false},{"text":"Take it as a personal attack","is_correct":false}]'::jsonb, 'Honest feedback, even when uncomfortable, often contains useful insight.', 2),
('00000000-0000-0000-0000-000000000012', 'Why do many investors say they value founders who''ve failed before?', '[{"text":"Because they''ve likely learned lessons that reduce future mistakes","is_correct":true},{"text":"Because failure guarantees future success","is_correct":false},{"text":"Because it makes for a more entertaining story","is_correct":false},{"text":"They don''t — investors avoid founders who''ve failed","is_correct":false}]'::jsonb, 'Experience with failure often means a founder has already learned things the hard way.', 3),
('00000000-0000-0000-0000-000000000012', 'What''s a good first step after a setback?', '[{"text":"Figure out specifically what didn''t work and why","is_correct":true},{"text":"Immediately start a completely different, unrelated idea","is_correct":false},{"text":"Avoid thinking about it at all","is_correct":false},{"text":"Blame factors you can''t control and stop there","is_correct":false}]'::jsonb, 'Understanding the specific cause of a setback is what makes the lesson actionable.', 4),

-- Intro to Digital Tools (013)
('00000000-0000-0000-0000-000000000013', 'Why might a founder use online tools instead of doing everything by hand?', '[{"text":"They save time and reduce simple mistakes","is_correct":true},{"text":"Digital tools are always free","is_correct":false},{"text":"They remove the need to plan at all","is_correct":false},{"text":"They''re only useful for large companies","is_correct":false}]'::jsonb, 'Good tools handle repetitive work so founders can focus on bigger decisions.', 0),
('00000000-0000-0000-0000-000000000013', 'What is "cloud storage"?', '[{"text":"Saving files online so they can be accessed from anywhere","is_correct":true},{"text":"A type of physical hard drive","is_correct":false},{"text":"A way to delete files permanently","is_correct":false},{"text":"A social media platform","is_correct":false}]'::jsonb, 'Cloud storage keeps your files safe and accessible from any device with internet.', 1),
('00000000-0000-0000-0000-000000000013', 'Why is it useful to organise files clearly from the start?', '[{"text":"It saves time finding things later as a project grows","is_correct":true},{"text":"Organisation has no real benefit","is_correct":false},{"text":"Only large teams need organised files","is_correct":false},{"text":"It''s only relevant for schoolwork","is_correct":false}]'::jsonb, 'Good organisation habits early on save a lot of frustration as things grow.', 2),
('00000000-0000-0000-0000-000000000013', 'What is a spreadsheet commonly used for in a small business?', '[{"text":"Tracking numbers like sales, costs, or inventory","is_correct":true},{"text":"Designing a logo","is_correct":false},{"text":"Hosting a website","is_correct":false},{"text":"Sending text messages","is_correct":false}]'::jsonb, 'Spreadsheets are a simple, flexible way to track and calculate numbers over time.', 3),
('00000000-0000-0000-0000-000000000013', 'Why might a founder use a shared document with their team?', '[{"text":"So everyone can see updates in real time","is_correct":true},{"text":"To keep information hidden from teammates","is_correct":false},{"text":"It''s required by every business","is_correct":false},{"text":"To avoid ever having meetings","is_correct":false}]'::jsonb, 'Shared documents keep everyone on the same page without constant back-and-forth.', 4),

-- Website & App Basics (014)
('00000000-0000-0000-0000-000000000014', 'What is the main purpose of a business website?', '[{"text":"To help people learn about and trust the business","is_correct":true},{"text":"It has no real purpose today","is_correct":false},{"text":"Only to display a logo","is_correct":false},{"text":"To replace talking to customers entirely","is_correct":false}]'::jsonb, 'A website is often the first place people go to learn about and evaluate a business.', 0),
('00000000-0000-0000-0000-000000000014', 'Why does website loading speed matter?', '[{"text":"Slow sites cause visitors to leave before seeing anything","is_correct":true},{"text":"Speed has no effect on visitors","is_correct":false},{"text":"Only search engines care about speed","is_correct":false},{"text":"Faster sites are always more expensive","is_correct":false}]'::jsonb, 'People lose patience quickly — a slow site can lose visitors before they even see your content.', 1),
('00000000-0000-0000-0000-000000000014', 'What does "mobile-friendly" mean for a website?', '[{"text":"It displays and works well on phones, not just computers","is_correct":true},{"text":"It can only be viewed on a phone","is_correct":false},{"text":"It requires downloading an app","is_correct":false},{"text":"It has no images","is_correct":false}]'::jsonb, 'Most visitors browse on phones, so a site needs to work well on small screens too.', 2),
('00000000-0000-0000-0000-000000000014', 'Why is clear navigation important on a website?', '[{"text":"It helps visitors find what they''re looking for quickly","is_correct":true},{"text":"Navigation doesn''t affect the visitor experience","is_correct":false},{"text":"Confusing layouts are usually more exciting","is_correct":false},{"text":"It''s only relevant for online shops","is_correct":false}]'::jsonb, 'If people can''t find what they need quickly, they often leave the site altogether.', 3),
('00000000-0000-0000-0000-000000000014', 'What is an "app", broadly speaking?', '[{"text":"A piece of software designed to help users do a specific task","is_correct":true},{"text":"Any website with a colourful design","is_correct":false},{"text":"A type of business licence","is_correct":false},{"text":"A physical device","is_correct":false}]'::jsonb, 'Apps are built to help people accomplish specific tasks, whether on phones or computers.', 4),

-- Staying Safe Online (015)
('00000000-0000-0000-0000-000000000015', 'What''s a smart habit when it comes to passwords?', '[{"text":"Use a different, strong password for each account","is_correct":true},{"text":"Reuse the same simple password everywhere","is_correct":false},{"text":"Share your password with anyone who asks","is_correct":false},{"text":"Write passwords in a public post","is_correct":false}]'::jsonb, 'Unique, strong passwords limit the damage if one account is ever compromised.', 0),
('00000000-0000-0000-0000-000000000015', 'What should you do if a message asks for personal or financial information unexpectedly?', '[{"text":"Be cautious and verify before sharing anything","is_correct":true},{"text":"Reply immediately with everything asked for","is_correct":false},{"text":"Forward it to as many people as possible","is_correct":false},{"text":"Click every link in the message","is_correct":false}]'::jsonb, 'Unexpected requests for personal info are a common scam tactic — always verify first.', 1),
('00000000-0000-0000-0000-000000000015', 'Why should young founders be careful about what they post publicly?', '[{"text":"Public posts can be seen by anyone, including people you don''t know","is_correct":true},{"text":"Posting publicly has no real risk","is_correct":false},{"text":"Only large businesses need to think about this","is_correct":false},{"text":"Private information should always be posted for reach","is_correct":false}]'::jsonb, 'Once something is public, you can''t fully control who sees or shares it.', 2),
('00000000-0000-0000-0000-000000000015', 'What is "two-factor authentication"?', '[{"text":"An extra security step beyond just a password","is_correct":true},{"text":"A second, weaker password","is_correct":false},{"text":"A way to recover a forgotten username","is_correct":false},{"text":"A type of online payment","is_correct":false}]'::jsonb, 'Two-factor authentication adds a second check (like a code sent to your phone) to keep accounts secure.', 3),
('00000000-0000-0000-0000-000000000015', 'What should you do if something online makes you feel uncomfortable or unsafe?', '[{"text":"Tell a trusted adult and avoid engaging further","is_correct":true},{"text":"Keep it to yourself and hope it stops","is_correct":false},{"text":"Respond aggressively to the person","is_correct":false},{"text":"Share it publicly for attention","is_correct":false}]'::jsonb, 'Telling a trusted adult early is always the safest response to something that feels wrong online.', 4)
on conflict do nothing;

-- Keep quizzes.question_count in sync with the rows actually seeded above.
update quizzes q
set question_count = (select count(*) from quiz_questions where quiz_id = q.id)
where q.id in (
  '00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000003',
  '00000000-0000-0000-0000-000000000004','00000000-0000-0000-0000-000000000005','00000000-0000-0000-0000-000000000006',
  '00000000-0000-0000-0000-000000000007','00000000-0000-0000-0000-000000000008','00000000-0000-0000-0000-000000000009',
  '00000000-0000-0000-0000-000000000010','00000000-0000-0000-0000-000000000011','00000000-0000-0000-0000-000000000012',
  '00000000-0000-0000-0000-000000000013','00000000-0000-0000-0000-000000000014','00000000-0000-0000-0000-000000000015'
);
